#!/bin/bash
/var/daemon-configs/shellScript/init.sh
process_name=daemon-service
config_file_name=/var/daemon-configs/daemonConfig.ini
start() {
    echo "start ${process_name}"
    ${process_name} -c ${config_file_name} 2>>/dev/null
    echo "OK"
}

stop() {
	${process_name} ctl shutdown
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

